# Generated by Django 5.0.2 on 2024-02-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notite',
            fields=[
                ('id_notita', models.IntegerField(primary_key=1, serialize=False)),
                ('text_notita', models.CharField(max_length=500)),
            ],
        ),
    ]
